### ISSUE TITLE
error during running modelv1

### ISSUE THREAD

**Issue by srinathdwivedi** [Sshanu/Relation-Extraction#11]
i am trying to copy modelv1 code in editor and run it, following error is occurring:
/home/srinath/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/srinath/phd_programme/relation_classification/model_1.py", line 71, in <module>
    cell = tf.contrib.rnn.BasicLSTMCell(word_state_size)
NameError: name 'word_state_size' is not defined
i would like to know how to resolve this.

**Comment by Sshanu** [comment]
you did not copy the code properly. I have defined word_state_size in the code. Please check the code again.

**Comment by srinathdwivedi** [comment]
is it in the same file? in modlev1.jpynb, i checked it is only in two places that is:
with tf.variable_scope("word_lstm1"):
    cell = tf.contrib.rnn.BasicLSTMCell(word_state_size)
    state_series, current_state = tf.nn.dynamic_rnn(cell, embedded_word[0], sequence_length=path_length[0], initial_state=init_states[0])
    state_series_word1 = tf.reduce_max(state_series, axis=1)

with tf.variable_scope("word_lstm2"):
    cell = tf.contrib.rnn.BasicLSTMCell(word_state_size)
    state_series, current_state = tf.nn.dynamic_rnn(cell, embedded_word[1], sequence_length=path_length[1], initial_state=init_states[0])
    state_series_word2 = tf.reduce_max(state_series, axis=1)

but error is still continuing 
Traceback (most recent call last):
  File "/home/snd/phd_programme/relation_classification/model_1.py", line 71, in <module>
    cell = tf.contrib.rnn.BasicLSTMCell(word_state_size)
NameError: name 'word_state_size' is not defined
please tell me how to resolve this
i also tried to run in jupyter notebook but problem still continue.

**Comment by Sshanu** [comment]
check the modelv8

**Comment by srinathdwivedi** [comment]
okay, thanks.
i got it.
