### ISSUE TITLE
Can't find the "checkpoint" folder

### ISSUE THREAD

**Issue by Emily-zcy** [Sshanu/Relation-Extraction#19]
Hello, Shannu
I am trying to run the models in the LCA Shortest Path folder. But I didn't find the "checkpoint" folder and its files. Like that,
    word_embd_dir = '../checkpoint/word_embd_wiki'
    pos_embd_dir = '../checkpoint/pos_embd'
    dep_embd_dir = '../checkpoint/dep_embd'
    model_dir = '../checkpoint/modelv8'
So I couldn't run it successfully. Do these files need to be generated by myself? Or did you not upload it to GitHub?  If it's the latter, can you share them with me?
Best wishes.

**Comment by Sshanu** [comment]
uncomment these commands in the file: https://github.com/Sshanu/Relation-Classification-using-Bidirectional-LSTM-Tree/blob/master/LSTM%20Seq%20and%20Tree/model3v1.ipynb

f = open('data/word_embedding', 'rb')
word_embedding = pickle.load(f)
f.close()
sess.run(embedding_init, feed_dict={embedding_placeholder:word_embedding})
word_embedding_saver.save(sess, word_embd_dir + '/word_embd')
