### ISSUE TITLE
Hi,I have re-run your modelv4 on LCA shortest path,but the test accuracy is only 9%...

### ISSUE THREAD

**Issue by SilverBullet330** [Sshanu/Relation-Extraction#8]
i used glove embedding, and the train accuracy is 95%, it looks nice, but when i test the test-set, the accuracy is only 9%, i dont know how it happened...

**Comment by Sshanu** [comment]
which test-set are you using?

**Comment by SilverBullet330** [comment]
i just use the test-set file(test_pathsv1) in you data directory, i'm not sure is there something wrong when i transform Glove file into vocab list and word_embedding. can you upload the code which transform Glove file and word2vec file into vocab list and word_embedding. i want try again with your code.i also want to know the reason why you don't set the word_embeding's trainable=false, i'm a greener in ML, thank you!

**Comment by Sshanu** [comment]
https://drive.google.com/open?id=1YihuwLDGtQQ-I0_sbxt_spyIL1Ew_chx

**Comment by arunzz** [comment]
I also got 9%. Kindly let know what was followed to solve this.

**Comment by Sshanu** [comment]
Please try using this word embedding https://drive.google.com/open?id=1YihuwLDGtQQ-I0_sbxt_spyIL1Ew_chx

**Comment by arunzz** [comment]
I downloaded and uncommented the word_embed load part. But it is extremely slow and running out of memory. Can i load it and just run the test or should i train again using this? Kindly let know. Thanks for your response.

**Comment by arunzz** [comment]
Hi Shanu

I used glove file you shared for embedding word. Still the same result 9%
I am using the testpathv1 which you have. Should i again preprocess testfilefull and try? Pls let know. 

I uncommented the code of placing glove embeddings into graph node for lookup.

**Comment by SilverBullet330** [comment]
the problem is not in testfile,because i have use the latest stanford parser to parse the original file fully and compare two file(my testpath file and testpathv1 in data), they are almost same...

**Comment by SilverBullet330** [comment]
after you uncommented the word_embed load part, have you put the tf.global_variables_initializer() code after the load part, if the load part before the initializer, the loaded embedding will be covered

**Comment by arunzz** [comment]
Thank you. I did initialize after the word embed load. Now the accuracy for test data is 53%
Pls let know.
I restored the model and run with test data alone. While testing i didnt use glove embeddings. Should i use? If so pls let know how. I tried restoring the glove embedding from disk but it just gives 7%

**Comment by Sshanu** [comment]
Only before training for the first time you have to restore glove embedding.
Then you can just restore the whole model for testing or further training

**Comment by arunzz** [comment]
I did the same but accuracy is very less (5%)
I have attached the same. Can you please verify if anything  is wrong in
this.


Regards
Arun

**Comment by arunzz** [comment]
Hi Shanu

I have attached two files.
1) modelv4.txt - shortest path - 56% accuracy
2) model3v2 - Sequence and dep - 57% accuracy.
Can you please check if anything is wrong in this?


[modelv4.txt](https://github.com/Sshanu/Relation-Classification/files/1978706/modelv4.txt)
[model3v2.txt](https://github.com/Sshanu/Relation-Classification/files/1978707/model3v2.txt)

**Comment by Sshanu** [comment]
First pre train the model for 2 epochs using:
_, _loss, step, _summary = sess.run([optimizer_seq, loss_seq, global_step_seq, summary], feed_dict)

then train the model using:
 _, _loss, step, _summary = sess.run([train_op, total_loss, global_step_dep, summary], feed_dict)

**Comment by arunzz** [comment]
Thank you. I will do that for sequential model.
Any tip for the shortest path model?

I am evaluating both in terms of speed and memory also . So trying out both.

Regards
Arun

**Comment by Sshanu** [comment]
Use dropout wrapper in LSTM.

Instead of giving the information like POS Tags try predicting them which will improve the hidden states' grammatical info.

Train the POS and Dependency embeddings by Skip Gram Model or any other technique.
Then use these embeddings for initializing the embeddings in the model.
Try these it will help in increasing the accuracy.

You can experiment with the hyperparameters also, as I didn't experiment a lot with the hypermeters.

**Comment by arunzz** [comment]
Sure I will definitely try the POS and dependency embeddings. But first I tried the entity pretraining. But I am stuck with the below error. However the same tensors work for training the full model when i comment out the entity pre-training. Could you please take a look at the attached code? Or please share the model for pretrained entity. I will take that and run 10 epochs for complete model. 
[model3v2.txt](https://github.com/Sshanu/Relation-Classification/files/1979041/model3v2.txt)

InvalidArgumentError (see above for traceback): All dimensions except 1 must match. Input 1 has shape [1 100] and doesn't match input 0 with shape [13 100].

**Comment by arunzz** [comment]
Hi Shanu

Can you please let know what are these two variables and what it represents in the dependency tree

  Position of words in LCA Paths in whole sequence
    sp_pos = tf.placeholder(tf.int32, [batch_size, 2, max_len_path], name="sp_pos")
  Position in whole sequence of the children in Dependency Tree of words in LCA Paths 
   sp_childs = tf.placeholder(tf.int32, [batch_size, 2, max_len_path, max_num_child], name="sp_childs")

**Comment by Sshanu** [comment]
sp_pos : Position of words from the lca path in the full sentence.
sp_child : Position of children in the full sentence
where children : children of every word from the lca path in the dependency tree

**Comment by arunzz** [comment]
Thank you, can you please tell for num_child and num_child_sp.
The summation of children is ok but there are two loops for num_child and num_child_sp with matmul and childsum.
Can you please tell why matmul loop is required.
